# Generated by Django 4.2 on 2024-02-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('naziv',), 'verbose_name_plural': 'Kategorije'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='naziv',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='cijena',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='is_sold',
            new_name='dostupno',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='kategorija',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='naziv',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='opis',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='slika',
        ),
    ]
