# Generated by Django 4.2 on 2024-02-13 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_category_options_rename_name_category_naziv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='dostupno',
        ),
    ]
