# Generated by Django 4.2 on 2024-02-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_remove_item_dostupno'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dostupno',
            field=models.BooleanField(default=True),
        ),
    ]
