# Generated by Django 4.2 on 2024-02-13 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_item_dostupno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='dostupno',
        ),
    ]
